# Generated by Django 2.0.6 on 2018-07-13 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='article2tag',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='articleupdown',
            unique_together=set(),
        ),
    ]
